language: python
dist: bionic
install:
  - pip install --upgrade pip
  - git clone https://github.com/sampotter/python-embree
  - pushd python-embree; pip install .; popd
  - pip install .
script:
  - python -m unittest discover tests
