language: python

python:
  - "3.6"

dist: bionic

addons:
  apt:
    update: true

before_install:
  - sudo apt-get -y install libcgal-dev

install:
  # upgrade pip (unnecessary?)
  - pip install --upgrade pip

  # get packages
  - pip install cython

  # get embree and set up environment variables
  - wget https://github.com/embree/embree/releases/download/v3.13.2/embree-3.13.2.x86_64.linux.tar.gz
  - tar xvf embree-3.13.2.x86_64.linux.tar.gz
  - pushd embree-3.13.2.x86_64.linux; source embree-vars.sh; popd

  # install python-embree
  - git clone https://github.com/sampotter/python-embree
  - pushd python-embree; pip install .; popd

  # install python-flux
  - python setup.py build_ext -i

script:
  - python -m unittest discover tests
